### ISSUE TITLE
CLRF

### ISSUE THREAD

**Issue by jasonLaster** [ryanjduffy/parse-script-tags#3]
we should make sure this works consistently on a MAC:

https://github.com/ryanjduffy/parse-script-tags/blob/master/index.js#L63-L65

**Comment by Garbee** [comment]
https://stackoverflow.com/a/14063413/2604748

Looks like a constant can be used to solve getting the right line ending for the host OS.

**Comment by ryanjduffy** [comment]
Put together a (hopefully) x-platform-safe change in #4. @jasonLaster - can you give it a test and let me know if it works as expected on windows? My windows box is currently in PDX so I can't test myself easily. :)

**Comment by ryanjduffy** [comment]
@jasonLaster - Updated npm to 0.1.2 with this fix!
