### ISSUE TITLE
Remove parse5 dependency

### ISSUE THREAD

**Issue by jasonLaster** [ryanjduffy/parse-script-tags#6]
Parse5 adds 500KB to the parser worker. We should try to reduce the footprint by using a portion of the lib or removing it:

Here is where it is introduced
https://github.com/ryanjduffy/parse-script-tags/commit/917f668d1388396db7061909b8ec7c075243e381

Here is a doc on [bundling](https://github.com/devtools-html/debugger.html/blob/master/docs/bundling.md)

### After 
<img width="1129" alt="screen shot 2017-11-25 at 12 34 27 pm" src="https://user-images.githubusercontent.com/254562/33233037-0efc5826-d1de-11e7-8352-a1054e2c8050.png">

### Before
<img width="1038" alt="screen shot 2017-11-25 at 12 34 18 pm" src="https://user-images.githubusercontent.com/254562/33233038-0f0ec308-d1de-11e7-9f95-020b089ad890.png">

### Actual
<img width="1037" alt="screen shot 2017-11-25 at 12 34 07 pm" src="https://user-images.githubusercontent.com/254562/33233030-04cc74f8-d1de-11e7-9dce-034e5cb5494e.png">

### Analyzer

<img width="1047" alt="screen shot 2017-11-25 at 12 44 01 pm" src="https://user-images.githubusercontent.com/254562/33233083-b9ed8318-d1de-11e7-85ca-7836f80a3ecf.png">

**Comment by ryanjduffy** [comment]
Doesn't appear to be a way to greatly minimize the size usage of `parse5` so the alternatives would be:

* Find a smaller alternative
* Implement my own fragment parsing (ugh)
* ...?

cc: @inikulin in case you have suggestions on `parse5` usage. Thanks!!

**Comment by ryanjduffy** [comment]
I should admit that using a full html5-compliant parser for this task is nice but also overkill.

**Comment by ryanjduffy** [comment]
Added a much simpler (and therefore less feature-filled) parser and published as part of 0.1.5.
